import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/admindashboard">Admindashboard</Link>
        </li>
        <li>
          <Link to="/adminfeedback">Adminfeedback</Link>
        </li>
        <li>
          <Link to="/adminfeedbacktwo">AdminfeedbackTwo</Link>
        </li>
        <li>
          <Link to="/adminfeedbackthree">AdminfeedbackThree</Link>
        </li>
        <li>
          <Link to="/admincreateboard">Admincreateboard</Link>
        </li>
        <li>
          <Link to="/adminroadmap">Adminroadmap</Link>
        </li>
        <li>
          <Link to="/admineditroadmap">Admineditroadmap</Link>
        </li>
        <li>
          <Link to="/adminusers">Adminusers</Link>
        </li>
        <li>
          <Link to="/adminsettings">Adminsettings</Link>
        </li>
        <li>
          <Link to="/adminchangelog">Adminchangelog</Link>
        </li>
        <li>
          <Link to="/userroadmap">Userroadmap</Link>
        </li>
        <li>
          <Link to="/admineditdashboard">Admineditdashboard</Link>
        </li>
        <li>
          <Link to="/usercreatepost">Usercreatepost</Link>
        </li>
        <li>
          <Link to="/screenthirteen">ScreenThirteen</Link>
        </li>
      </ul>
    </div>
  );
};

export default Home;
